---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/bosh --version
    register: bosh_test_output
  - name: bosh --version
    debug:
      msg: '{{ bosh_test_output.stdout }}'
