---
- name: Testing andrewrothstein.bosh
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'bosh --version'
      ansible.builtin.command: /usr/local/bin/bosh --version
      changed_when: false
      register: bosh_test_output
    - name: Output of 'bosh --version'
      ansible.builtin.debug:
        msg: '{{ bosh_test_output.stdout }}'
